BASE: ['']
TOOLBOX_MODE: "only_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 30
  LR: 9e-3
  MODEL_FILE_NAME: MMPD_Full_ST3_Aug_ST56_TVT40_MMPD_tscan
  DATA:
    INFO:
      LIGHT: [1]  # 1 - LED-Low, 2 - LED-high, 3 - Incandescent, 4 - Nature
      MOTION: [1] # 1 - Stationary, 2 - Rotation, 3 - Talking, 4 - Walking
      EXERCISE: [2] # 1 - True, 2 - False
      SKIN_COLOR: [3] # Fitzpatrick Scale Skin Types - 3, 4, 5, 6
      GENDER: [1, 2]  # 1 - Male, 2 - Female
      GLASSER: [1, 2] # 1 - True, 2 - False
      HAIR_COVER: [1, 2] # 1 - True, 2 - False
      MAKEUP: [1, 2] # 1 - True, 2 - False
    FS: 30
    DATASET: MMPD_Full_ST3_Aug_ST56_TVT40
    DO_PREPROCESS: False                 # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:   "/playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/TVT_MMPD_FULL_ST6_FP_SEG"          # Raw dataset path, need to be updated
    CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold/train"      # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized' ]
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
VALID:
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/NLUT_UBFC_DST_FP_SEG"          # need to be updated
    CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold/val"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized' ]
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
# TEST:
#   METRICS: ['MAE','RMSE','MAPE','Pearson']
#   USE_LAST_EPOCH: True                      # to use provided validation dataset to find the best epoch, should be false
#   DATA:
#     INFO:
#       LIGHT: [2]  # 1 - LED-Low, 2 - LED-high, 3 - Incandescent, 4 - Nature
#       MOTION: [1] # 1 - Stationary, 2 - Rotation, 3 - Talking, 4 - Walking
#       EXERCISE: [2] # 1 - True, 2 - False
#       SKIN_COLOR: [4] # Fitzpatrick Scale Skin Types - 3, 4, 5, 6
#       GENDER: [1, 2]  # 1 - Male, 2 - Female
#       GLASSER: [1, 2] # 1 - True, 2 - False
#       HAIR_COVER: [1, 2] # 1 - True, 2 - False
#       MAKEUP: [1, 2] # 1 - True, 2 - False
#     FS: 30
#     DATASET: MMPD
#     DO_PREPROCESS: False                  # if first time, should be true
#     DATA_FORMAT: NDCHW
#     DATA_PATH:   "/playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/Mini-MMPD-rPPG"          # Raw dataset path, need to be updated
#     CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold/test"      # Processed dataset save path, need to be updated
#     EXP_DATA_NAME: ""
#     BEGIN: 0.0
#     END: 1.0
#     PREPROCESS:
#       DATA_TYPE: [ 'DiffNormalized','Standardized' ]
#       LABEL_TYPE: DiffNormalized
#       DO_CHUNK: True
#       CHUNK_LENGTH: 180
#       DYNAMIC_DETECTION: False
#       DYNAMIC_DETECTION_FREQUENCY : 180
#       CROP_FACE: True
#       LARGE_FACE_BOX: True
#       LARGE_BOX_COEF: 1.5
#       H: 72
#       W: 72
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  USE_LAST_EPOCH: True                      # to use provided validation dataset to find the best epoch, should be false
  DATA:
    INFO:
      LIGHT: [1, 4]  # 1 - LED-Low, 2 - LED-high, 3 - Incandescent, 4 - Nature
      MOTION: [1] # 1 - Stationary, 2 - Rotation, 3 - Talking, 4 - Walking
      EXERCISE: [2] # 1 - True, 2 - False
      SKIN_COLOR: [6] # Fitzpatrick Scale Skin Types - 3, 4, 5, 6
      GENDER: [1, 2]  # 1 - Male, 2 - Female
      GLASSER: [1, 2] # 1 - True, 2 - False
      HAIR_COVER: [1, 2] # 1 - True, 2 - False
      MAKEUP: [1, 2] # 1 - True, 2 - False
    FS: 30
    DATASET: MMPD
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:   "/playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/MMPD-rPPG"          # Raw dataset path, need to be updated
    CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold/test"      # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized' ]
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: Tscan
  TSCAN:
    FRAME_DEPTH: 10
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  # MODEL_PATH: "PreTrainedModels/MMPD_Full_ST3_Aug_ST56_TVT40_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len180/MMPD_Full_ST3_Aug_ST56_TVT40_MMPD_tscan_Epoch29.pth"
  # Shows some promise
  # MODEL_PATH: "PreTrainedModels/MMPD_Full_ST3_Aug_ST56_NO_SEG_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len180/MMPD_Full_ST3_Aug_ST56_NO_SEG_MMPD_tscan_Epoch29.pth"
  # MODEL_PATH:     "PreTrainedModels/MMPD_Full_ST3_Aug_ST56_V3_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len180/MMPD_Full_ST3_Aug_ST56_V3_MMPD_tscan_Epoch29.pth"
  # MODEL_PATH:    "PreTrainedModels/MMPD_Full_ST3_Aug_ST56_V2_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len180/MMPD_Full_ST3_Aug_ST56_V2_MMPD_tscan_Epoch29.pth"
  # MODEL_PATH:   "PreTrainedModels/MMPD_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len180/MMPD_Full_ST3_MMPD_tscan_Epoch29.pth"
  # Shows some promise
  # MODEL_PATH:   "PreTrainedModels/MMPD_Full_ST3_Aug_ST56_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len180/MMPD_Full_ST3_Aug_ST56_MMPD_tscan_Epoch29.pth"
  # MODEL_PATH:   "PreTrainedModels/MMPD_ST3_Aug_ST56_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len180/MMPD_MMPD_tscan_Epoch29.pth"
  # MODEL_PATH:   "PreTrainedModels/MMPD_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len180/MMPD_ST3_MMPD_tscan_Epoch29.pth"
  # Above is Mini-MMPD that got overwritten by Full, no longer really relevant!