BASE: ['']
TOOLBOX_MODE: "only_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 30
  LR: 9e-3
  MODEL_FILE_NAME: MMPD
  DATA:
    INFO:
      LIGHT: [1, 2]  # 1 - LED-Low, 2 - LED-high, 3 - Incandescent, 4 - Nature
      MOTION: [1] # 1 - Stationary, 2 - Rotation, 3 - Talking, 4 - Walking
      EXERCISE: [2] # 1 - True, 2 - False
      SKIN_COLOR: [3] # Fitzpatrick Scale Skin Types - 3, 4, 5, 6
      GENDER: [1, 2]  # 1 - Male, 2 - Female
      GLASSER: [1, 2] # 1 - True, 2 - False
      HAIR_COVER: [1, 2] # 1 - True, 2 - False
      MAKEUP: [1, 2] # 1 - True, 2 - False
    FS: 30
    DATASET: MMPD
    DO_PREPROCESS: False                 # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:   "/playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/MMPD-rPPG"          # Raw dataset path, need to be updated
    CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold/test"      # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized' ]
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
# TRAIN:
#   BATCH_SIZE: 4
#   EPOCHS: 30
#   LR: 9e-3
#   MODEL_FILE_NAME: MMPD_Full_ST3_Aug_ST56_RVM_Combined_MMPD_tscan
#   DATA:
#     INFO:
#       LIGHT: [1]  # 1 - LED-Low, 2 - LED-high, 3 - Incandescent, 4 - Nature
#       MOTION: [1] # 1 - Stationary, 2 - Rotation, 3 - Talking, 4 - Walking
#       EXERCISE: [2] # 1 - True, 2 - False
#       SKIN_COLOR: [3] # Fitzpatrick Scale Skin Types - 3, 4, 5, 6
#       GENDER: [1, 2]  # 1 - Male, 2 - Female
#       GLASSER: [1, 2] # 1 - True, 2 - False
#       HAIR_COVER: [1, 2] # 1 - True, 2 - False
#       MAKEUP: [1, 2] # 1 - True, 2 - False
#     FS: 30
#     DATASET: MMPD_Full_ST3_Aug_ST56_RVM_Combined
#     DO_PREPROCESS: True                 # if first time, should be true
#     DATA_FORMAT: NDCHW
#     DATA_PATH:   "/playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/NLUT_MMPD_FULL_ST6_RVM"          # Raw dataset path, need to be updated
#     CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold/train"      # Processed dataset save path, need to be updated
#     EXP_DATA_NAME: ""
#     BEGIN: 0.0
#     END: 1.0
#     PREPROCESS:
#       DATA_TYPE: [ 'DiffNormalized','Standardized' ]
#       LABEL_TYPE: DiffNormalized
#       DO_CHUNK: True
#       CHUNK_LENGTH: 180
#       CROP_FACE:
#         DO_CROP_FACE: True
#         USE_LARGE_FACE_BOX: True
#         LARGE_BOX_COEF: 1.5
#         DETECTION:
#           DO_DYNAMIC_DETECTION: False
#           DYNAMIC_DETECTION_FREQUENCY : 30
#           USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
#       RESIZE:
#         H: 72
#         W: 72
VALID:
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/NLUT_UBFC_DST_FP_SEG"          # need to be updated
    CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold/val"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized' ]
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
# TEST:
#   METRICS: ['MAE','RMSE','MAPE','Pearson']
#   USE_LAST_EPOCH: True                      # to use provided validation dataset to find the best epoch, should be false
#   DATA:
#     INFO:
#       LIGHT: [2]  # 1 - LED-Low, 2 - LED-high, 3 - Incandescent, 4 - Nature
#       MOTION: [1] # 1 - Stationary, 2 - Rotation, 3 - Talking, 4 - Walking
#       EXERCISE: [2] # 1 - True, 2 - False
#       SKIN_COLOR: [4] # Fitzpatrick Scale Skin Types - 3, 4, 5, 6
#       GENDER: [1, 2]  # 1 - Male, 2 - Female
#       GLASSER: [1, 2] # 1 - True, 2 - False
#       HAIR_COVER: [1, 2] # 1 - True, 2 - False
#       MAKEUP: [1, 2] # 1 - True, 2 - False
#     FS: 30
#     DATASET: MMPD
#     DO_PREPROCESS: False                  # if first time, should be true
#     DATA_FORMAT: NDCHW
#     DATA_PATH:   "/playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/Mini-MMPD-rPPG"          # Raw dataset path, need to be updated
#     CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold/test"      # Processed dataset save path, need to be updated
#     EXP_DATA_NAME: ""
#     BEGIN: 0.0
#     END: 1.0
#     PREPROCESS:
#       DATA_TYPE: [ 'DiffNormalized','Standardized' ]
#       LABEL_TYPE: DiffNormalized
#       DO_CHUNK: True
#       CHUNK_LENGTH: 180
#       DYNAMIC_DETECTION: False
#       DYNAMIC_DETECTION_FREQUENCY : 180
#       CROP_FACE: True
#       LARGE_FACE_BOX: True
#       LARGE_BOX_COEF: 1.5
#       H: 72
#       W: 72
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  USE_LAST_EPOCH: True                      # to use provided validation dataset to find the best epoch, should be false
  DATA:
    INFO:
      LIGHT: [1, 2, 3]  # 1 - LED-Low, 2 - LED-high, 3 - Incandescent, 4 - Nature
      MOTION: [1] # 1 - Stationary, 2 - Rotation, 3 - Talking, 4 - Walking
      EXERCISE: [2] # 1 - True, 2 - False
      SKIN_COLOR: [4, 5, 6] # Fitzpatrick Scale Skin Types - 3, 4, 5, 6
      GENDER: [1, 2]  # 1 - Male, 2 - Female
      GLASSER: [1, 2] # 1 - True, 2 - False
      HAIR_COVER: [1, 2] # 1 - True, 2 - False
      MAKEUP: [1, 2] # 1 - True, 2 - False
    FS: 30
    DATASET: MMPD
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH:   "/playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/MMPD-rPPG"          # Raw dataset path, need to be updated
    CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold/test"      # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized' ]
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      CROP_FACE:
        DO_CROP_FACE: True
        USE_LARGE_FACE_BOX: True
        LARGE_BOX_COEF: 1.5
        DETECTION:
          DO_DYNAMIC_DETECTION: False
          DYNAMIC_DETECTION_FREQUENCY : 30
          USE_MEDIAN_FACE_BOX: False    # This should be used ONLY if dynamic detection is used
      RESIZE:
        H: 72
        W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: Tscan
  TSCAN:
    FRAME_DEPTH: 10
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  #
  # Full Res, ST3, just low LED and high LED, stationary
  # MODEL_PATH: "PreTrainedModels/MMPD_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse/MMPD_Epoch29.pth"
  #
  # TVT40, Augmented full res low LED ST3 by multiplying pixels by 0.4 (adjust darkness) (Combined)
  # MODEL_PATH: "PreTrainedModels/MMPD_Full_ST3_Aug_ST56_TVT40_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse/MMPD_Full_ST3_Aug_ST56_TVT40_MMPD_tscan_Epoch29.pth"
  # 
  # V1, Augmented full res low LED ST3 with ST5-6 (Combined)
  # MODEL_PATH: "PreTrainedModels/MMPD_Full_ST3_Aug_ST56_Combined_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse/MMPD_Full_ST3_Aug_ST56_TVT40_MMPD_tscan_Epoch29.pth"
  #
  # V1, Augmented full res low LED ST3 with ST5-6 (RVM) (Combined)
  # MODEL_PATH: "PreTrainedModels/MMPD_Full_ST3_Aug_ST56_RVM_Combined_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse/MMPD_Full_ST3_Aug_ST56_RVM_Combined_MMPD_tscan_Epoch29.pth"
  #
  # V4, Augmented full res low LED ST3 with ST5-6 (Just image 2677 from FFHQ), stricter seg masks (Combined)
  # MODEL_PATH: "PreTrainedModels/MMPD_Full_ST3_Aug_ST56_V4_Combined_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse/MMPD_Full_ST3_Aug_ST56_V4_Combined_MMPD_tscan_Epoch29.pth"
  #
  # V3, Augmented full res low LED ST3 with ST5-6 (Just image 2677 from FFHQ) without FP Segmentation Masks (Combined)
  # MODEL_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/rPPG-Toolbox/PreTrainedModels/MMPD_Full_ST3_Aug_ST56_NO_SEG_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse/MMPD_Full_ST3_Aug_ST56_NO_SEG_MMPD_tscan_Epoch29.pth"
  #
  # === Non-combined below ===
  #
  # V1, Augmented full res low LED ST3 with ST5-6 (RVM)
  # MODEL_PATH: "PreTrainedModels/MMPD_Full_ST3_Aug_ST56_RVM_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Crop_faceTrue_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len30_Median_face_boxFalse/MMPD_Full_ST3_Aug_ST56_RVM_MMPD_tscan_Epoch29.pth"
  #
  # Full Res Low LED, ST3, Stationary
  # MODEL_PATH:   "PreTrainedModels/MMPD_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len180/MMPD_Full_ST3_MMPD_tscan_Epoch29.pth"
  #
  # V1, Augmented full res low LED ST3 with ST5-6
  # MODEL_PATH:   "PreTrainedModels/MMPD_Full_ST3_Aug_ST56_SizeW72_SizeH72_ClipLength180_DataTypeDiffNormalized_Standardized_LabelTypeDiffNormalized_Large_boxTrue_Large_size1.5_Dyamic_DetFalse_det_len180/MMPD_Full_ST3_Aug_ST56_MMPD_tscan_Epoch29.pth"
