BASE: ['']
TOOLBOX_MODE: "train_and_test"      # "train_and_test"  or "only_test"
TRAIN:
  BATCH_SIZE: 4
  EPOCHS: 30
  LR: 9e-3
  MODEL_FILE_NAME: UBFC_PURE_efficientphys
  DATA:
    FS: 30
    DATASET: UBFC
    DO_PREPROCESS: True               # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/playpen-nas-hdd/UNC_Google_Physio/UBFC-rPPG/DATASET_2_backup/DATASET_2/train"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold/train"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Standardized']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
# TRAIN:
#   BATCH_SIZE: 4
#   EPOCHS: 30
#   LR: 9e-3
#   MODEL_FILE_NAME: MAUBFC_SMALL_HP_MAUBFC_SMALL_HP_PURE_tscan
#   DATA:
#     FS: 30
#     DATASET: MAUBFC_SMALL_HP_PICKED
#     DO_PREPROCESS: False              # if first time, should be true
#     DATA_FORMAT: NDCHW
#     DATA_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/MAUBFC_SMALL_HP_PICKED"                     # Raw dataset path, need to be updated
#     CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold/train"    # Processed dataset save path, need to be updated
#     EXP_DATA_NAME: ""
#     BEGIN: 0.0
#     END: 1.0
#     PREPROCESS:
#       DATA_TYPE: ['DiffNormalized','Standardized']
#       LABEL_TYPE: DiffNormalized
#       DO_CHUNK: True
#       CHUNK_LENGTH: 180
#       DYNAMIC_DETECTION: False
#       DYNAMIC_DETECTION_FREQUENCY : 180
#       CROP_FACE: True
#       LARGE_FACE_BOX: True
#       LARGE_BOX_COEF: 1.5
#       H: 72
#       W: 72
# TRAIN:
#   BATCH_SIZE: 4
#   EPOCHS: 30
#   LR: 9e-3
#   MODEL_FILE_NAME: MAPURE_LARGE_HP_MAPURE_LARGE_HP_AFRL_tscan
#   DATA:
#     FS: 30
#     DATASET: MAPURE_LARGE_AU
#     DO_PREPROCESS: False               # if first time, should be true
#     DATA_FORMAT: NDCHW
#     DATA_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/MAPURE_LARGE_AU"                     # Raw dataset path, need to be updated
#     CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold/train"    # Processed dataset save path, need to be updated
#     EXP_DATA_NAME: ""
#     BEGIN: 0.0
#     END: 0.8
#     PREPROCESS:
#       DATA_TYPE: ['DiffNormalized','Standardized']
#       LABEL_TYPE: DiffNormalized
#       DO_CHUNK: True
#       CHUNK_LENGTH: 180
#       DYNAMIC_DETECTION: False
#       DYNAMIC_DETECTION_FREQUENCY : 180
#       CROP_FACE: True
#       LARGE_FACE_BOX: True
#       LARGE_BOX_COEF: 1.5
#       H: 72
#       W: 72
VALID:
  DATA:
    FS: 30
    DATASET: MAPURE_LARGE_HP_PICKED
    DO_PREPROCESS: False                  # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/MAPURE_LARGE_HP_PICKED"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold/val"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.8
    END: 1.0
    PREPROCESS:
      DATA_TYPE: [ 'DiffNormalized','Standardized' ]
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
TEST:
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  USE_LAST_EPOCH: True                     # to use provided validation dataset to find the best epoch, should be false
  DATA:
    FS: 30
    DATASET: PURE
    DO_PREPROCESS: False                    # if first time, should be true
    DATA_FORMAT: NDCHW
    DATA_PATH: "/playpen-nas-hdd/UNC_Google_Physio/PURE/RawData/test"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS:
      DATA_TYPE: ['Standardized']
      LABEL_TYPE: DiffNormalized
      DO_CHUNK: True
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: False
      DYNAMIC_DETECTION_FREQUENCY : 180
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.5
      H: 72
      W: 72
# TEST:
#   METRICS: ['MAE','RMSE','MAPE','Pearson']
#   USE_LAST_EPOCH: True                     # to use provided validation dataset to find the best epoch, should be false
#   DATA:
#     FS: 30
#     DATASET: UBFC
#     DO_PREPROCESS: False                    # if first time, should be true
#     DATA_FORMAT: NDCHW
#     DATA_PATH: "/playpen-nas-hdd/UNC_Google_Physio/UBFC-rPPG/DATASET_2_backup/DATASET_2/test"                     # Raw dataset path, need to be updated
#     CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold/test"    # Processed dataset save path, need to be updated
#     EXP_DATA_NAME: ""
#     BEGIN: 0.0
#     END: 1.0
#     PREPROCESS:
#       DATA_TYPE: [ 'Normalized','Standardized' ]
#       LABEL_TYPE: Normalized
#       DO_CHUNK: True
#       CHUNK_LENGTH: 180
#       DYNAMIC_DETECTION: False
#       DYNAMIC_DETECTION_FREQUENCY : 180
#       CROP_FACE: True
#       LARGE_FACE_BOX: True
#       LARGE_BOX_COEF: 1.5
#       H: 72
#       W: 72
# TEST:
#   METRICS: ['MAE','RMSE','MAPE','Pearson']
#   USE_LAST_EPOCH: True                     # to use provided validation dataset to find the best epoch, should be false
#   DATA:
#     FS: 30
#     DATASET: AFRL
#     DO_PREPROCESS: False                    # if first time, should be true
#     DATA_FORMAT: NDCHW
#     DATA_PATH: "/playpen-temp/users/xliu0/AFRL"                     # Raw dataset path, need to be updated
#     CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold"    # Processed dataset save path, need to be updated
#     EXP_DATA_NAME: ""
#     BEGIN: 0.0
#     END: 1.0
#     PREPROCESS:
#       DATA_TYPE: [ 'DiffNormalized','Standardized' ]
#       LABEL_TYPE: DiffNormalized
#       DO_CHUNK: True
#       CHUNK_LENGTH: 180
#       DYNAMIC_DETECTION: False
#       DYNAMIC_DETECTION_FREQUENCY : 180
#       CROP_FACE: True
#       LARGE_FACE_BOX: True
#       LARGE_BOX_COEF: 1.5
#       H: 72
#       W: 72
# TEST:
#   METRICS: ['MAE','RMSE','MAPE','Pearson']
#   USE_LAST_EPOCH: True
#   DATA:
#     FS: 35
#     DATASET: UBFC-PHYS
#     DO_PREPROCESS: False                    # if first time, should be true
#     DATA_FORMAT: NDCHW
#     DATA_PATH: "/playpen-nas-hdd/UNC_Google_Physio/UBFC-PHYS/used"                     # Raw dataset path, need to be updated
#     CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold/test"    # Processed dataset save path, need to be updated
#     EXP_DATA_NAME: ""
#     BEGIN: 0.0
#     END: 1.0
#     PREPROCESS:
#       DATA_TYPE: [ 'Normalized','Standardized' ]
#       LABEL_TYPE: Normalized
#       DO_CHUNK: True
#       CHUNK_LENGTH: 180
#       DYNAMIC_DETECTION: True
#       DYNAMIC_DETECTION_FREQUENCY : 1
#       CROP_FACE: True
#       LARGE_FACE_BOX: True
#       LARGE_BOX_COEF: 1.1
#       H: 72
#       W: 72
# TEST:
#   METRICS: ['MAE','RMSE','MAPE','Pearson']
#   USE_LAST_EPOCH: True                      # to use provided validation dataset to find the best epoch, should be false
#   DATA:
#     FS: 30
#     DATASET: MMPD
#     DO_PREPROCESS: True                    # if first time, should be true
#     DATA_FORMAT: NDCHW
#     DATA_PATH:   "/playpen-nas-ssd/akshay/UNC_Google_Physio/datasets/Mini-MMPD-rPPG"          # Raw dataset path, need to be updated
#     CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/preprocessed_gold/test"      # Processed dataset save path, need to be updated
#     EXP_DATA_NAME: ""
#     BEGIN: 0.0
#     END: 1.0
#     PREPROCESS:
#       DATA_TYPE: [ 'Normalized','Standardized' ]
#       LABEL_TYPE: Normalized
#       DO_CHUNK: True
#       CHUNK_LENGTH: 180
#       DYNAMIC_DETECTION: False
#       DYNAMIC_DETECTION_FREQUENCY : 180
#       CROP_FACE: True
#       LARGE_FACE_BOX: True
#       LARGE_BOX_COEF: 1.5
#       H: 72
#       W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 1
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: EfficientPhys
  EFFICIENTPHYS:
    FRAME_DEPTH: 10
INFERENCE:
  BATCH_SIZE: 4
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
  MODEL_PATH: "" # /playpen-nas-ssd/akshay/UNC_Google_Physio/models/gold/MAUBFC_LARGE_HP_PICKED.pth
