BASE: ['']
TOOLBOX_MODE: "signal_method"      # "train_and_test"  or "only_test" or "signal_method"
SIGNAL:
  METHOD: ["POS"]
  METRICS: ['MAE','RMSE','MAPE','Pearson']
  DATA:
    FS: 35
    DATASET: UBFCPHYS_T3_FaceCropping_Median_1-1_HC
    DO_PREPROCESS: False               # if first time, should be true
    DATA_FORMAT: NDHWC
    DATA_PATH: "/playpen-nas-hdd/UNC_Google_Physio/UBFC-PHYS/used"                     # Raw dataset path, need to be updated
    CACHED_PATH: "/playpen-nas-ssd/akshay/UNC_Google_Physio/phys_preprocessed"    # Processed dataset save path, need to be updated
    EXP_DATA_NAME: ""
    BEGIN: 0.0
    END: 1.0
    PREPROCESS :
      DATA_TYPE: ['Raw']
      LABEL_TYPE: Raw
      DO_CHUNK: False
      CHUNK_LENGTH: 180
      DYNAMIC_DETECTION: True
      DYNAMIC_DETECTION_FREQUENCY : 1
      CROP_FACE: True
      LARGE_FACE_BOX: True
      LARGE_BOX_COEF: 1.1
      H: 72
      W: 72
INFERENCE:
  EVALUATION_METHOD: "FFT"        # "FFT" or "peak detection"
